# Window Customization
scrolling:
  history: 10000
  multiplier: 3
background_opacity: .9
window.dynamic_title: true

# Font Customization
font:
  normal:
    family: Fira Code
    style: Regular
  bold:
    family: Fira Code
    style: Bold
  italic:
    family: Fira Code
    style: Italic
  size: 15
  use_thin_strokes: false
  debug:
    persistent_logging: false
draw_bold_text_with_bright_colors: true

cursor:
  style: Block
  unfocused_hollow: true

key_bindings:
  - { key: N, mods: Control, action: SpawnNewInstance }
