# Window Customization
window:
  startup_mode: Fullscreen
  padding:
    x: 4
    y: 4
  decorations: full
  dynamic_title: true

env:
  TERM: xterm-256color
    #TERM: alacritty

# Scrolling
scrolling.muultiplier: 3
scrolling:
  history: 10000
  multiplier: 3
  autoscroll: true
background_opacity: .75

# Font Customization
font:
  normal:
    family: Menlo
    style: Regular
  bold:
    family: Menlo
    style: Bold
  italic:
    family: Menlo
    style: Italic
  size: 14
  use_thin_strokes: false
  debug:
    persistent_logging: false
draw_bold_text_with_bright_colors: false

live_config_reload: true

cursor:
  style: Block
  unfocused_hollow: true

key_bindings:
  - { key: Home,                    chars: "\x1bOH",   mode: AppCursor   }
  - { key: Home,                    chars: "\x1b[H",   mode: ~AppCursor  }
  - { key: End,                     chars: "\x1bOF",   mode: AppCursor   }
  - { key: End,                     chars: "\x1b[F",   mode: ~AppCursor  }
  
  - { key: PageUp,   mode: Vi,      action: ScrollPageUp                 }
  - { key: PageDown, mode: Vi,      action: ScrollPageDown               }
    #  - { key: PageUp,                  action: ScrollPageUp                 }
    #  - { key: PageDown,                action: ScrollPageDown               }
  - { key: Tab,      mods: Shift,   chars: "\x1b[Z"                      }

  - { key: K,              mods: Command, mode: ~Vi, chars: "\x0c"            }
  - { key: K,              mods: Command,            action: ClearHistory     }
  - { key: Key0,           mods: Command,            action: ResetFontSize    }
  - { key: Equals,         mods: Command,            action: IncreaseFontSize }
  - { key: Minus,          mods: Command,            action: DecreaseFontSize }
  - { key: V,              mods: Command,            action: Paste            }
  - { key: C,              mods: Command,            action: Copy             }
  - { key: Paste,                                    action: Paste            }
  - { key: Copy,                                     action: Copy             }
  - { key: C,              mods: Command, mode: Vi,  action: ClearSelection   }
  - { key: H,              mods: Command,            action: Hide             }
  - { key: M,              mods: Command,            action: Minimize         }
  - { key: Q,              mods: Command,            action: Quit             }
  - { key: W,              mods: Command,            action: Quit             }
  - { key: N,              mods: Command,            action: SpawnNewInstance }
  - { key: F,              mods: Command|Control,    action: ToggleFullscreen }
  - { key: F,              mods: Command,            action: SearchForward    }
  - { key: B,              mods: Command,            action: SearchBackward   }


  # Vi Mode
  - { key: Space,  mods: Shift|Control,           action: ToggleViMode            }
  - { key: Space,  mods: Shift|Control, mode: Vi, action: ScrollToBottom          }
  - { key: I,                           mode: Vi, action: ScrollToBottom          }
  - { key: Escape,                      mode: Vi, action: ClearSelection          }
  - { key: I,                           mode: Vi, action: ToggleViMode            }
  - { key: C,      mods: Control,       mode: Vi, action: ToggleViMode            }
  - { key: Y,      mods: Control,       mode: Vi, action: ScrollLineUp            }
  - { key: E,      mods: Control,       mode: Vi, action: ScrollLineDown          }
  - { key: G,                           mode: Vi, action: ScrollToTop             }
  - { key: G,      mods: Shift,         mode: Vi, action: ScrollToBottom          }
  - { key: B,      mods: Control,       mode: Vi, action: ScrollPageUp            }
  - { key: F,      mods: Control,       mode: Vi, action: ScrollPageDown          }
  - { key: U,      mods: Control,       mode: Vi, action: ScrollHalfPageUp        }
  - { key: D,      mods: Control,       mode: Vi, action: ScrollHalfPageDown      }
  - { key: Y,                           mode: Vi, action: Copy                    }
  - { key: Y,                           mode: Vi, action: ClearSelection          }
  - { key: Copy,                        mode: Vi, action: ClearSelection          }
  - { key: V,                           mode: Vi, action: ToggleNormalSelection   }
  - { key: V,      mods: Shift,         mode: Vi, action: ToggleLineSelection     }
  - { key: V,      mods: Control,       mode: Vi, action: ToggleBlockSelection    }
  - { key: V,      mods: Alt,           mode: Vi, action: ToggleSemanticSelection }
  - { key: Return,                      mode: Vi, action: Open                    }
  - { key: K,                           mode: Vi, action: Up                      }
  - { key: J,                           mode: Vi, action: Down                    }
  - { key: H,                           mode: Vi, action: Left                    }
  - { key: L,                           mode: Vi, action: Right                   }
  - { key: Up,                          mode: Vi, action: Up                      }
  - { key: Down,                        mode: Vi, action: Down                    }
  - { key: Left,                        mode: Vi, action: Left                    }
  - { key: Right,                       mode: Vi, action: Right                   }
  - { key: Key0,                        mode: Vi, action: First                   }
  - { key: Key4,   mods: Shift,         mode: Vi, action: Last                    }
  - { key: Key6,   mods: Shift,         mode: Vi, action: FirstOccupied           }
  - { key: H,      mods: Shift,         mode: Vi, action: High                    }
  - { key: M,      mods: Shift,         mode: Vi, action: Middle                  }
  - { key: L,      mods: Shift,         mode: Vi, action: Low                     }
  - { key: B,                           mode: Vi, action: SemanticLeft            }
  - { key: W,                           mode: Vi, action: SemanticRight           }
  - { key: E,                           mode: Vi, action: SemanticRightEnd        }
  - { key: B,      mods: Shift,         mode: Vi, action: WordLeft                }
  - { key: W,      mods: Shift,         mode: Vi, action: WordRight               }
  - { key: E,      mods: Shift,         mode: Vi, action: WordRightEnd            }
  - { key: Key5,   mods: Shift,         mode: Vi, action: Bracket                 }
  - { key: Slash,                       mode: Vi, action: SearchForward           }
  - { key: Slash,  mods: Shift,         mode: Vi, action: SearchBackward          }
  - { key: N,                           mode: Vi, action: SearchNext              }
  - { key: N,      mods: Shift,         mode: Vi, action: SearchPrevious          }




mouse_bindings:
  - { mouse: Right, action: PasteSelection }
  - { mouse: Middle, action: PasteSelection }

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: true
